version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    networks:
      - my-bridge
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  application:
    image: raquelpicanco/drf-app:1.2
    container_name: drf-app
    command: ./docker-entrypoint.sh
    networks:
      - my-bridge
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8000:8000
    depends_on:
      - db

networks:
  my-bridge:
    driver: bridge